version: "3.7"
services:
  checker:
    build:
      context: .
    environment:
      - ADMIN_PASS=admin
      - MONGODB=mongodb://mongo:27017
    volumes:
      - ./scripts:/scripts/
    networks:
      - ad-ctf-paas-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ad-ctf-paas-net

networks:
  ad-ctf-paas-net:
    external: true
    name: ad-ctf-paas-net